import type { Metadata } from 'next';
import './globals.css';
import Navbar from './components/layout/Navbar';
import Footer from './components/layout/Footer';
import localFont from 'next/font/local';

const fredoka = localFont({
  src: './fonts/Fredoka-VariableFont_wdth,wght.ttf',
  variable: '--font-fredoka',
  weight: '400',
  style: 'normal',
  display: 'swap',
});

const quicksand = localFont({
  src: './fonts/Quicksand-VariableFont_wght.ttf',
  variable: '--font-quicksand',
  weight: '400',
  style: 'normal',
  display: 'swap',
});

const parisienne = localFont({
  src: './fonts/Parisienne-Regular.ttf',
  variable: '--font-parisienne',
  weight: '400',
  style: 'normal',
  display: 'swap',
});

const poiretOne = localFont({
  src: './fonts/PoiretOne-Regular.ttf',
  variable: '--font-poiretone',
  weight: '400',
  style: 'normal',
  display: 'swap',
});

const petitFormalScript = localFont({
  src: './fonts/PetitFormalScript-Regular.ttf',
  variable: '--font-petit',
  weight: '400',
  style: 'normal',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Essense Burn',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${fredoka.variable} ${quicksand.variable} ${parisienne.variable} ${poiretOne.variable} ${petitFormalScript.variable} antialiased`}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
